# Generated by Django 4.1.5 on 2023-01-24 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.BigIntegerField()),
                ('plate_number', models.CharField(blank=True, max_length=15, null=True)),
                ('brand', models.CharField(max_length=15)),
                ('model', models.CharField(max_length=15)),
                ('year', models.SmallIntegerField()),
                ('gear', models.CharField(choices=[('Automatic', 'Auto'), ('Manual', 'Manu')], max_length=10)),
                ('fuel', models.CharField(choices=[('Diesel ', 'DZ'), ('Petrol', 'PT'), ('Hybrid', 'HY'), ('Electric', 'EL'), ('LPG', 'LPG')], max_length=10)),
                ('rent_per_day', models.IntegerField()),
                ('availibity', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.BigIntegerField()),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentacar.car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentacar.customer')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
            },
        ),
    ]
